// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID          uuid.UUID
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Characteristic struct {
	ID          uuid.UUID
	Description json.RawMessage
	ProductID   uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Product struct {
	ID          uuid.UUID
	Name        string
	Description json.RawMessage
	Price       float64
	ImageUrls   json.RawMessage
	StockAmount int32
	StoreID     uuid.UUID
	CategoryID  uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Seller struct {
	ID                    uuid.UUID
	GstNumber             string
	PanNumber             string
	PickupAddress         string
	BankAccountHolderName string
	BankAccountNumber     string
	IfscCode              string
	CreatedAt             time.Time
	UpdatedAt             time.Time
	UserID                uuid.UUID
}

type Store struct {
	ID        uuid.UUID
	Name      string
	OwnerID   uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID          uuid.UUID
	Email       sql.NullString
	PhoneNumber sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
